# Generated by Django 4.2 on 2023-08-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_contact_paymentdetails_remove_contactdetails_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentConfirm',
        ),
    ]
