# Generated by Django 4.2 on 2023-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='subject',
            field=models.CharField(blank=True, choices=[('maths', 'maths'), ('english', 'english'), ('socialscience', 'socialscience'), ('intergratedscience', 'intergratedscience'), ('kiswahili', 'kiswahili'), ('cre', 'cre'), ('ire', 'ire'), ('hre', 'hre')], default='paid', max_length=500, null=True),
        ),
    ]
