# Generated by Django 4.2 on 2023-08-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quizcategory_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='context_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='context_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
