# Generated by Django 4.2 on 2023-08-28 21:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_quizquestion_context_1_quizquestion_context_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='context_2',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='context_1',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
