# Generated by Django 4.2 on 2023-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_context_1_quizquestion_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='opt_5',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='opt_6',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='opt_7',
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='subject',
            field=models.CharField(blank=True, choices=[('maths', 'maths'), ('english', 'english'), ('socialscience', 'socialscience'), ('intergratedscience', 'intergratedscience'), ('kiswahili', 'kiswahili'), ('cre', 'cre'), ('ire', 'ire'), ('hre', 'hre')], default='maths', max_length=500, null=True),
        ),
    ]
