# Generated by Django 4.2.6 on 2024-01-20 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('question', models.TextField()),
                ('subject', models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Management', 'Management'), ('Nursing', 'Nursing'), ('English', 'English'), ('Marketing', 'Marketing'), ('Art', 'Art'), ('History', 'History'), ('Law', 'Law'), ('Economics', 'Economics'), ('Writing', 'Writing')], default='Accounting', max_length=500, null=True)),
                ('pages', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=500, null=True)),
                ('title', models.CharField(max_length=500)),
                ('files', models.FileField(blank=True, null=True, upload_to='company_doc/')),
                ('paid', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
