# Generated by Django 4.2.6 on 2024-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0002_remove_order_question_order_created_at_order_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hours',
            field=models.CharField(blank=True, choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='6', max_length=500, null=True),
        ),
    ]
