# Generated by Django 4.2.6 on 2024-01-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0003_alter_order_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hours',
            field=models.CharField(blank=True, choices=[('0', '0'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=500, null=True),
        ),
    ]
