# Generated by Django 4.2.6 on 2024-01-22 21:39

from django.db import migrations, models
import django.db.models.deletion
import storepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0004_alter_order_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_doc/', validators=[storepage.models.file_size])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storepage.order')),
            ],
        ),
    ]
