# Generated by Django 4.2.6 on 2024-01-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0006_orderfiles_instructions_alter_orderfiles_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
    ]
