# Generated by Django 4.2.6 on 2024-01-23 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0007_remove_order_description_remove_order_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
