# Generated by Django 4.2.6 on 2024-01-25 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storepage', '0008_orderfiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='level',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('College', 'College'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='0', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storepage.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
