# Generated by Django 4.2.6 on 2024-01-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0009_order_level_payinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.CharField(choices=[('High School', 'High School'), ('College', 'College'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='College', max_length=500),
        ),
    ]
